modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="cobblelvlcap"
version="${file.jarVersion}"
displayName="CobbleLvlCap"
description='''
A lightweight level cap progression system for Cobblemon.
Perfect for progression servers and balanced gameplay.
'''
authors="YourName"
displayURL="https://github.com/yourname/cobblelvlcap"

[[dependencies.cobblelvlcap]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblelvlcap]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblelvlcap]]
modId="cobblemon"
type="required"
versionRange="[1.7.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="cobblelvlcap.mixins.json"


